import { expect, test } from '@playwright/test';
import type { ElectronApplication } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expectNoSeriousA11yIssues } from './a11y';
import type { PageGlobals } from './helpers';
import { chooseMenuItem, launchApp, operatorPage, operatorReady } from './helpers';
import { launchMain, launchNode, nodeCode, nodesStatus, typePairing } from './nodes';
import { releaseServer } from './release-server';

/*
 * Updates (Session 14) against a release server on this computer, never a
 * real installer: the "installer" is generated bytes, checked by its
 * SHA-512, and installing at quit writes what it would run into a file
 * (DRASHTI_TEST_UPDATE_INSTALL) on both systems, since neither can install
 * a test build. Offered, downloaded (waiting while on air), held until
 * quit, never in Simple Mode; a node refused for its version offers Main's.
 */

/** The lines of some text that show, as the dialog shows them (its blank lines and indents aside). */
const lines = (text: string) =>
  text
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);

const menuHas = (app: ElectronApplication, id: string) =>
  app.evaluate(({ Menu }, itemId) => Menu.getApplicationMenu()?.getMenuItemById(itemId) !== null, id);

test('an update is offered with what changed, downloads (waiting while on air), and installs only at quit; Simple Mode never sees it', async () => {
  test.setTimeout(120_000);
  const installer = randomBytes(2 * 1024 * 1024);
  // Its notes are this version's CHANGELOG.md section, taken out as the Release workflow does for drashti-update.json.
  const notesFile = join(mkdtempSync(join(tmpdir(), 'drashti-update-notes-')), 'release-notes.md');
  execFileSync(process.execPath, [join('scripts', 'release-notes.mjs'), '--out', notesFile], {
    cwd: join(__dirname, '..', '..'),
  });
  const notes = readFileSync(notesFile, 'utf8').trim();
  const release = await releaseServer({ '9.9.9': installer }, '9.9.9', notes);
  const installLog = join(mkdtempSync(join(tmpdir(), 'drashti-update-e2e-')), 'install.json');
  try {
    const { app } = await launchApp({
      DRASHTI_UPDATE_URL: release.base,
      DRASHTI_TEST_UPDATE_INSTALL: installLog,
      DRASHTI_TEST_ON_AIR_HOOK: '1',
      DRASHTI_TEST_UPDATE_RATE: String(1024 * 1024),
    });
    const win = await operatorPage(app);
    await win.setViewportSize({ width: 1280, height: 720 });
    await operatorReady(win);
    // Help > Check for Updates…: offered.
    await chooseMenuItem(app, 'check-for-updates');
    const dialog = win.getByTestId('updates-dialog');
    await expect(dialog).toBeVisible();
    await dialog.getByTestId('updates-check').click();
    await expect(dialog.getByTestId('updates-offer')).toContainText('Drashti 9.9.9');
    // What changed, line by line, its first line first.
    const shown = dialog.getByTestId('updates-notes');
    await expect(shown).toBeVisible();
    expect(lines(await shown.innerText())).toEqual(lines(notes));
    await expectNoSeriousA11yIssues(win, 'updates, one offered');
    // On air: the download waits, and nothing is fetched until the stream is off air.
    await app.evaluate(() => {
      (globalThis as { drashtiTestOnAir?: (on: boolean) => void }).drashtiTestOnAir?.(true);
    });
    await dialog.getByTestId('updates-download').click();
    await expect(dialog).toContainText('Waiting: the stream is on air or recording');
    await new Promise((resolve) => setTimeout(resolve, 1500));
    expect(release.served()).toBe(0);
    await app.evaluate(() => {
      (globalThis as { drashtiTestOnAir?: (on: boolean) => void }).drashtiTestOnAir?.(false);
    });
    await expect(dialog.getByTestId('updates-ready')).toContainText('Downloaded and checked', {
      timeout: 30_000,
    });
    // Downloaded, nothing installs until an admin says so; then only at quit.
    expect(existsSync(installLog)).toBe(false);
    await dialog.getByTestId('updates-install-on-quit').click();
    await expect
      .poll(
        async () =>
          (await win.evaluate(() => (globalThis as PageGlobals).drashti.updates.view())).installOnQuit,
      )
      .toBe(true);
    await expectNoSeriousA11yIssues(win, 'updates, ready to install at quit');
    await dialog.getByRole('button', { name: 'Close', exact: true }).click();
    await expect(win.getByTestId('update-status')).toContainText('installs when Drashti quits');
    expect(existsSync(installLog)).toBe(false);
    // Simple Mode never sees it: no menu item, no word in the status bar, and the main process refuses.
    await win.getByRole('button', { name: 'Simple Mode' }).click();
    await expect(win.getByTestId('update-status')).toHaveCount(0);
    expect(await menuHas(app, 'check-for-updates')).toBe(false);
    const refused = await win.evaluate(() => (globalThis as PageGlobals).drashti.updates.check());
    expect(refused.ok).toBe(false);
    // Quit: it installs now (here, writes what it would run), and Drashti does not start again.
    await app.close();
    const ran = JSON.parse(readFileSync(installLog, 'utf8')) as { file: string; args: string[] };
    expect(readFileSync(ran.file).equals(installer)).toBe(true);
    if (process.platform === 'win32') expect(ran.args).toEqual(['--updated', '/S']);
  } finally {
    release.close();
  }
});

test('a node refused for its version offers to update to Main’s version, and quits to install it', async () => {
  test.setTimeout(150_000);
  const mainsVersion = randomBytes(256 * 1024);
  const release = await releaseServer({ '1.0.0-test.1': mainsVersion }, '1.0.0-test.1');
  const installLog = join(mkdtempSync(join(tmpdir(), 'drashti-node-update-e2e-')), 'install.json');
  const main = await launchMain({ DRASHTI_TEST_VERSION: '1.0.0-test.1' });
  const node = await launchNode({
    DRASHTI_TEST_VERSION: '1.0.0-test.2',
    DRASHTI_UPDATE_URL: release.base,
    DRASHTI_TEST_UPDATE_INSTALL: installLog,
  });
  try {
    await typePairing(node.page, main.port, await nodeCode(main.win));
    await expect(node.page.getByTestId('node-pair-error')).toContainText('Main runs Drashti 1.0.0-test.1');
    const offer = node.page.getByTestId('node-update');
    await expect(offer).toContainText('Main runs Drashti 1.0.0-test.1; this node runs 1.0.0-test.2');
    await expectNoSeriousA11yIssues(node.page, 'the node offering to match Main');
    await offer.getByTestId('node-update-check').click();
    await offer.getByTestId('node-update-download').click();
    await offer.getByTestId('node-update-install').click({ timeout: 30_000 });
    // Quit and install: the node quits, and the installer would run.
    await expect.poll(() => existsSync(installLog), { timeout: 20_000 }).toBe(true);
    const ran = JSON.parse(readFileSync(installLog, 'utf8')) as { file: string };
    expect(readFileSync(ran.file).equals(mainsVersion)).toBe(true);
    expect((await nodesStatus(main.win)).main.version).toBe('1.0.0-test.1');
  } finally {
    await node.app.close().catch(() => undefined);
    await main.app.close();
    release.close();
  }
});
