import type { ChildProcess } from 'node:child_process';
import { spawn, spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  statfsSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { ElectronApplication, Page } from '@playwright/test';
import { expect, test } from '@playwright/test';
import type { Device } from '../e2e/devices';
import { device, networkOn, pairByQr, pairingCode } from '../e2e/devices';
import type { OutputGlobals, PageGlobals } from '../e2e/helpers';
import { outputPage, outputPages, QUIET, setUpScreen } from '../e2e/helpers';
import type { MainRun, NodeRun } from '../e2e/nodes';
import { launchMain, launchNode, pairNode } from '../e2e/nodes';
import { freePort, TEST_KEY, testFfmpeg } from '../e2e/stream-helpers';
import type { OutputSample, ProcessSample, SoakEvent, SoakReport, SoakSample, Verdict } from './report';
import { growth, mainTotal, memoryOf, writeReport } from './report';

/*
 * The soak test (Session 15): a sabha that never stops, for three hours
 * (DRASHTI_SOAK_MINUTES), on CI's macOS and Windows runners, started by hand
 * (the Soak workflow). Placeholder words and media generated by FFmpeg here.
 *
 * Going on all the time: slides from a playlist every few seconds, with
 * picture and video backgrounds and dissolves; music now and then; messages
 * and a timer; the stream on air and a recording, to FFmpeg on this computer
 * (it throws the stream away); two outputs, an output node (a second
 * Drashti) with its own output, and a phone on the remote's feed. A
 * scheduled macro goes off six times, and a scheduled backup goes off while
 * on air (it waits) and goes on when the stream and the recording stop for
 * ten minutes halfway, as between two sabhas.
 *
 * Every few minutes (DRASHTI_SOAK_SAMPLE_MINUTES) it records each process's
 * memory and processor, each screen's late frames and paint times, the
 * logs' size and the free disk. It fails on a crash, a watchdog event, a
 * screen going black, or memory that keeps growing, and writes the curves
 * (test-results/soak: soak.html, soak.json, summary.md) either way.
 */

test.skip(QUIET, 'A real show for hours on real windows: runs on CI (the Soak workflow)');

const MINUTES = Math.max(5, Number(process.env['DRASHTI_SOAK_MINUTES'] ?? '180') || 180);
const SAMPLE_MS = Math.max(0.5, Number(process.env['DRASHTI_SOAK_SAMPLE_MINUTES'] ?? '3') || 3) * 60_000;
const OUT = join(process.cwd(), 'test-results', 'soak');
/** How often Next is pressed. */
const SLIDE_MS = 6000;

const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));
const at = (fraction: number) => fraction * MINUTES;

/** Media made here by the bundled FFmpeg: videos with a tone, pictures, and tones for the music. */
function makeMedia(ffmpeg: string, dir: string): string[] {
  const run = (args: string[]) => {
    const r = spawnSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-y', ...args], { stdio: 'pipe' });
    if (r.status !== 0)
      throw new Error(`FFmpeg could not make test media: ${r.stderr.toString().slice(0, 300)}`);
  };
  const files: string[] = [];
  for (const [i, hz] of [
    [1, 330],
    [2, 440],
    [3, 550],
  ] as const) {
    const out = join(dir, `Placeholder soak video ${String(i)}.mp4`);
    run([
      '-f',
      'lavfi',
      '-i',
      `testsrc2=size=1920x1080:rate=30`,
      '-f',
      'lavfi',
      '-i',
      `sine=frequency=${String(hz)}:sample_rate=48000`,
      '-t',
      '12',
      '-vf',
      `hue=h=${String(i * 90)}`,
      '-c:v',
      'libx264',
      '-preset',
      'veryfast',
      '-g',
      '30',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      out,
    ]);
    files.push(out);
  }
  for (const [i, colour] of [
    [1, '0x1d4e89'],
    [2, '0x7f1d1d'],
  ] as const) {
    const out = join(dir, `Placeholder soak picture ${String(i)}.png`);
    run(['-f', 'lavfi', '-i', `color=c=${colour}:size=1920x1080`, '-frames:v', '1', out]);
    files.push(out);
  }
  for (const [i, hz] of [
    [1, 262],
    [2, 392],
  ] as const) {
    const out = join(dir, `Placeholder soak tone ${String(i)}.wav`);
    run(['-f', 'lavfi', '-i', `sine=frequency=${String(hz)}:sample_rate=44100`, '-t', '30', out]);
    files.push(out);
  }
  for (const i of [1, 2, 3]) {
    const out = join(dir, `Placeholder soak words ${String(i)}.txt`);
    const verses = Array.from(
      { length: 6 },
      (_, v) => `Placeholder words ${String(i)}, slide ${String(v + 1)}\nનમૂના પંક્તિ ${String(v + 1)}\n`,
    );
    writeFileSync(out, `[Verse]\n${verses.join('\n')}`);
    files.push(out);
  }
  return files;
}

/** FFmpeg on this computer standing in for YouTube, throwing the stream away; started again whenever it ends. */
function listener(ffmpeg: string, port: number): { stop(): void } {
  let child: ChildProcess | null = null;
  let stopped = false;
  const start = () => {
    child = spawn(
      ffmpeg,
      [
        '-hide_banner',
        '-loglevel',
        'error',
        '-listen',
        '1',
        '-i',
        `rtmp://127.0.0.1:${String(port)}/live2/${TEST_KEY}`,
        '-c',
        'copy',
        '-f',
        'null',
        '-',
      ],
      { stdio: 'ignore', windowsHide: true },
    );
    child.once('exit', () => {
      if (!stopped) setTimeout(start, 500);
    });
  };
  start();
  return {
    stop: () => {
      stopped = true;
      child?.kill('SIGKILL');
    },
  };
}

/** The files in a folder (and its subfolders), together (MB). */
function folderMb(dir: string): number {
  if (!existsSync(dir)) return 0;
  let bytes = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) bytes += folderMb(p) * 1024 * 1024;
    else bytes += statSync(p).size;
  }
  return bytes / (1024 * 1024);
}

/** Each process of an instance, by what it is: memory (working set) and processor since the last time asked. */
function processes(app: ElectronApplication): Promise<{ label: string; memoryKb: number; cpu: number }[]> {
  return app.evaluate(({ app: a, webContents }) => {
    const pages = new Map<number, string>();
    for (const wc of webContents.getAllWebContents()) {
      const url = wc.getURL();
      const label = url.includes('index.html')
        ? 'Operator window'
        : url.includes('output.html')
          ? 'Outputs'
          : url.includes('audio.html')
            ? 'Audio player'
            : url.includes('stream.html')
              ? 'Program (stream)'
              : url.includes('node.html')
                ? 'Node window'
                : 'Other windows';
      pages.set(wc.getOSProcessId(), label);
    }
    return a.getAppMetrics().map((m) => ({
      label:
        m.type === 'Browser'
          ? 'Main process'
          : m.type === 'GPU'
            ? 'GPU'
            : m.type === 'Utility'
              ? 'Workers'
              : (pages.get(m.pid) ?? 'Other windows'),
      memoryKb: m.memory.workingSetSize,
      cpu: m.cpu.percentCPUUsage,
    }));
  });
}

/** Whether a screen shows nothing at all: its picture, made small, has no pixel brighter than near-black. */
async function isBlack(page: Page): Promise<boolean> {
  const png = (await page.screenshot({ scale: 'css' })).toString('base64');
  return page.evaluate(async (data) => {
    const bytes = Uint8Array.from(atob(data), (c) => c.charCodeAt(0));
    const bitmap = await createImageBitmap(new Blob([bytes], { type: 'image/png' }));
    const canvas = new OffscreenCanvas(96, 54);
    const ctx = canvas.getContext('2d');
    if (!ctx) return false;
    ctx.drawImage(bitmap, 0, 0, 96, 54);
    const pixels = ctx.getImageData(0, 0, 96, 54).data;
    let brightest = 0;
    for (let i = 0; i < pixels.length; i += 4)
      brightest = Math.max(brightest, pixels[i] ?? 0, pixels[i + 1] ?? 0, pixels[i + 2] ?? 0);
    return brightest < 12;
  }, png);
}

const pct = (values: number[], p: number): number | null => {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * p))] ?? null;
};

/** A screen's paints and late frames since the last time asked. */
async function screenSample(
  page: Page,
  name: string,
  seen: Map<Page, { paints: number; late: number }>,
): Promise<OutputSample> {
  const { log, late } = await page.evaluate(() => {
    const g = globalThis as OutputGlobals;
    return {
      log: (g.drashtiPaintLog ?? []).map((p) => p.paintedAt - p.sentAt),
      late: g.drashtiLateFrames ?? 0,
    };
  });
  const before = seen.get(page) ?? { paints: 0, late: 0 };
  // The log keeps the last 20,000 paints: more than a sample's worth.
  const fresh = log.slice(
    Math.max(0, Math.min(before.paints, log.length) - Math.max(0, log.length - 20_000)),
  );
  seen.set(page, { paints: log.length, late });
  return {
    name,
    paints: fresh.length,
    medianMs: pct(fresh, 0.5),
    p90Ms: pct(fresh, 0.9),
    worstMs: fresh.length > 0 ? Math.max(...fresh) : null,
    lateFrames: Math.max(0, late - before.late),
    black: await isBlack(page),
  };
}

/** Watchdog events in an instance's log: a window crashed, hung or was given up on. */
function watchdogLines(userData: string): number {
  const dir = join(userData, 'logs');
  if (!existsSync(dir)) return 0;
  return readdirSync(dir)
    .filter((f) => /^drashti(\.\d+)?\.log$/u.test(f))
    .flatMap((f) => readFileSync(join(dir, f), 'utf8').split('\n'))
    .filter((l) => /Watchdog: .* (crashed|hung|gave-up)/u.test(l)).length;
}

/** How many times a log says something (Main's log). */
function logCount(userData: string, pattern: RegExp): number {
  const dir = join(userData, 'logs');
  if (!existsSync(dir)) return 0;
  return readdirSync(dir)
    .filter((f) => /^drashti(\.\d+)?\.log$/u.test(f))
    .flatMap((f) => readFileSync(join(dir, f), 'utf8').split('\n'))
    .filter((l) => pattern.test(l)).length;
}

/** "YYYY-MM-DD" and "HH:MM" for a moment, in this computer's time (as schedules read them). */
function localWhen(ms: number): { date: string; time: string } {
  const d = new Date(ms);
  const two = (n: number) => String(n).padStart(2, '0');
  return {
    date: `${String(d.getFullYear())}-${two(d.getMonth() + 1)}-${two(d.getDate())}`,
    time: `${two(d.getHours())}:${two(d.getMinutes())}`,
  };
}

/** The next whole minute at least `aheadMs` from now. */
const minuteAfter = (aheadMs: number) => Math.ceil((Date.now() + aheadMs) / 60_000) * 60_000;

test('a sabha that never stops', async () => {
  test.setTimeout((MINUTES + 45) * 60_000);
  mkdirSync(OUT, { recursive: true });
  const ffmpeg = testFfmpeg();
  expect(ffmpeg, 'the bundled FFmpeg (node scripts/fetch-ffmpeg.mjs)').not.toBeNull();
  const work = mkdtempSync(join(tmpdir(), 'drashti-soak-'));
  const media = makeMedia(ffmpeg ?? '', work);
  const recordings = join(work, 'Recordings');
  const backups = join(work, 'Backups');
  mkdirSync(recordings);
  mkdirSync(backups);

  const startedAt = Date.now();
  const minute = () => Math.round(((Date.now() - startedAt) / 60_000) * 10) / 10;
  const events: SoakEvent[] = [];
  const note = (what: string) => {
    events.push({ minute: minute(), what });
  };
  const samples: SoakSample[] = [];
  let main: MainRun | null = null;
  let node: NodeRun | null = null;
  let phone: Device | null = null;
  let rtmp: { stop(): void } | null = null;
  const exits: string[] = [];

  const report = (verdicts: Verdict[]): SoakReport => ({
    os: `${process.platform} ${process.arch}`,
    startedAt: new Date(startedAt).toISOString(),
    minutes: MINUTES,
    samples,
    events,
    verdicts,
  });

  try {
    // ---- Main, with two outputs, the network and fake camera and microphone for the stream --------
    main = await launchMain({ DRASHTI_TEST_FAKE_DEVICES: '1' });
    const { app, win, userData } = main;
    app.process().once('exit', (code) => {
      exits.push(`Main stopped (exit code ${String(code)})`);
    });
    await win.setViewportSize({ width: 1280, height: 720 });
    const imported = await win.evaluate(async (paths) => {
      const d = (globalThis as PageGlobals).drashti;
      const r = await d.library.importPaths(paths);
      return r.ok ? r.run.totals.failed : -1;
    }, media);
    expect(imported).toBe(0);
    await setUpScreen(win, 'Main Hall', 0);
    await setUpScreen(win, 'Overflow', 1);
    await expect.poll(() => outputPages(app).length).toBe(2);

    // The show: a playlist of words, videos and pictures, dissolving; music; a message; a timer; a macro at times.
    const show = await win.evaluate(async () => {
      const d = (globalThis as PageGlobals).drashti;
      const listed = await d.library.listPresentations();
      const words = listed.filter((p) => p.name.startsWith('Placeholder soak words')).map((p) => p.id);
      const all = await d.library.listMedia();
      const named = (start: string) => all.filter((m) => m.name.startsWith(start)).map((m) => m.id);
      const [v1 = '', v2 = '', v3 = ''] = named('Placeholder soak video');
      const [p1 = '', p2 = ''] = named('Placeholder soak picture');
      const tones = named('Placeholder soak tone');
      const [w1 = '', w2 = '', w3 = ''] = words;
      const dissolve = await d.library.setDefaultTransition({ kind: 'dissolve', durationMs: 1000 });
      if (!dissolve.ok) throw new Error(dissolve.message);
      const made = await d.playlists.create('Placeholder soak sabha', null, false);
      if (!made.ok) throw new Error(made.message);
      const playlistId = made.ids[0] ?? '';
      const added = await d.playlists.addItems(playlistId, null, [
        { kind: 'header', label: 'Placeholder welcome' },
        { kind: 'presentation', presentationId: w1 },
        { kind: 'media', mediaId: v1 },
        { kind: 'presentation', presentationId: w2 },
        { kind: 'media', mediaId: p1 },
        { kind: 'presentation', presentationId: w3 },
        { kind: 'media', mediaId: v2 },
        { kind: 'media', mediaId: p2 },
        { kind: 'media', mediaId: v3 },
      ]);
      if (!added.ok) throw new Error(added.message);
      const music = await d.music.create('Placeholder soak music');
      if (!music.ok || !music.id) throw new Error('no music');
      await d.music.addTracks(music.id, tones, null);
      const template = await d.messages.create({
        name: 'Placeholder parking',
        template: 'Car {plate} please move',
        fields: {},
      });
      if (!template.ok) throw new Error(template.message);
      const timer = await d.timers.create({
        name: 'Placeholder sabha clock',
        kind: 'countdown',
        durationMs: 45 * 60_000,
        targetTime: null,
        allowsOverrun: true,
      });
      if (!timer.ok) throw new Error(timer.message);
      return { playlistId, firstPicture: p1, musicId: music.id, templateId: template.id, timerId: timer.id };
    });
    // The macro shows a message at its times (one date each, this computer's time).
    const macroTimes = [0.06, 0.22, 0.39, 0.56, 0.72, 0.89].map((f) => minuteAfter(at(f) * 60_000));
    const macro = await win.evaluate(
      ({ templateId, times }) =>
        (globalThis as PageGlobals).drashti.macros.save(null, {
          name: 'Placeholder scheduled notice',
          color: '#2f9e44',
          actions: [{ kind: 'showMessage', templateId, values: { plate: 'SOAK' } }],
          schedules: times.map((t, i) => ({
            id: `soak-${String(i)}`,
            days: [],
            date: t.date,
            time: t.time,
            enabled: true,
          })),
        }),
      { templateId: show.templateId, times: macroTimes.map(localWhen) },
    );
    expect(macro.ok).toBe(true);
    note(`a macro set to run by itself at ${macroTimes.map((t) => localWhen(t).time).join(', ')}`);

    // ---- the output node, with its own output ---------------------------------------------------------
    node = await launchNode();
    node.app.process().once('exit', (code) => {
      exits.push(`The node stopped (exit code ${String(code)})`);
    });
    const nodeId = await pairNode(main, node);
    const lobby = await win.evaluate(async () => {
      const r = await (globalThis as PageGlobals).drashti.screens.createGroup('Lobby');
      if (!r.ok) throw new Error(r.message);
      return r.snapshot.groups.find((g) => g.name === 'Lobby')?.id ?? '';
    });
    await expect
      .poll(async () =>
        win.evaluate(
          async (id) =>
            (
              (await (globalThis as PageGlobals).drashti.screens.get()).nodes.find((n) => n.id === id)
                ?.displays ?? []
            ).length,
          nodeId,
        ),
      )
      .toBeGreaterThanOrEqual(2);
    const nodeDisplay = await win.evaluate(
      async (id) =>
        ((await (globalThis as PageGlobals).drashti.screens.get()).nodes.find((n) => n.id === id)?.displays ??
          [])[1]?.id ?? -1,
      nodeId,
    );
    const assigned = await win.evaluate(
      ({ group, nodeId, display }) =>
        (globalThis as PageGlobals).drashti.screens.assignNodeDisplay(group, nodeId, display),
      { group: lobby, nodeId, display: nodeDisplay },
    );
    expect(assigned.ok).toBe(true);
    const nodeOutput = await outputPage(node.app);
    note('an output node paired, its output showing the Lobby group');

    // ---- a phone on the remote's feed ---------------------------------------------------------------
    const { base } = await networkOn(win);
    phone = await device('chromium');
    await pairByQr(phone.page, base, await pairingCode(win, 'remote', 'Placeholder soak phone'), '/remote');
    note('a phone paired as a remote, following the feed');

    // ---- the stream and a recording -----------------------------------------------------------------
    const port = await freePort();
    rtmp = listener(ffmpeg ?? '', port);
    await app.evaluate(({ dialog }, into) => {
      dialog.showOpenDialog = () => Promise.resolve({ canceled: false, filePaths: [into] });
    }, recordings);
    await win.getByTestId('open-stream').click();
    await expect
      .poll(async () => {
        const s = await win.evaluate(() => (globalThis as PageGlobals).drashti.stream.status());
        return s.inputs.cameras.length > 0 && s.inputs.microphones.length > 0;
      })
      .toBe(true);
    const ready = await win.evaluate(
      async ({ port, key }) => {
        const d = (globalThis as PageGlobals).drashti;
        const s = await d.stream.status();
        const { profiles, activeId } = await d.stream.profiles();
        const p = profiles.find((x) => x.id === activeId);
        if (!p) return 'no profile';
        const saved = await d.stream.saveProfile(p.id, {
          name: 'Placeholder soak stream',
          url: `rtmp://127.0.0.1:${String(port)}/live2`,
          preset: 'weak',
          camera: s.inputs.cameras[0] ?? null,
          sound: s.inputs.microphones[0] ?? null,
          soundDelayMs: 0,
          mixOwnSound: true,
        });
        if (!saved.ok) return saved.message;
        const kept = await d.stream.setKey(p.id, key);
        if (!kept.ok) return kept.message;
        const folder = await d.stream.pickFolder();
        return folder.ok ? 'ok' : folder.message;
      },
      { port, key: TEST_KEY },
    );
    expect(ready).toBe('ok');
    const goLive = async () => {
      await win.evaluate(async () => {
        const d = (globalThis as PageGlobals).drashti;
        await d.stream.startRecording();
        await d.stream.goLive({ confirmed: true });
      });
      await expect
        .poll(
          async () =>
            (await win.evaluate(() => (globalThis as PageGlobals).drashti.stream.status())).live.state,
          {
            timeout: 60_000,
          },
        )
        .toBe('live');
      note('on air and recording');
    };
    const offAir = async () => {
      await win.evaluate(async () => {
        const d = (globalThis as PageGlobals).drashti;
        await d.stream.end({ confirmed: true });
        await d.stream.stopRecording();
      });
      note('the stream ended and the recording stopped (between sabhas)');
    };
    await goLive();

    // ---- the sabha, until the time is up ---------------------------------------------------------------
    const dispatch = (command: Parameters<PageGlobals['drashti']['engine']['dispatch']>[0]) =>
      win.evaluate((c) => (globalThis as PageGlobals).drashti.engine.dispatch(c), command);
    // Something is always up behind the words: a picture first; then each video or picture item's.
    await dispatch({
      type: 'setBackground',
      background: { kind: 'media', mediaId: show.firstPicture, media: 'image', fit: 'fill', loop: false },
    });
    await dispatch({ type: 'startTimer', timerId: show.timerId });
    const firstItem = async () =>
      win.evaluate(async (playlistId) => {
        const d = (globalThis as PageGlobals).drashti;
        const items = (await d.playlists.items(playlistId)).filter((i) => i.kind !== 'header');
        return items[0]?.id ?? '';
      }, show.playlistId);
    const startOver = async () =>
      dispatch({ type: 'playItem', playlistId: show.playlistId, itemId: await firstItem() });
    await startOver();
    note('the sabha began');

    const end = startedAt + MINUTES * 60_000;
    const seen = new Map<Page, { paints: number; late: number }>();
    let nextSlide = Date.now() + SLIDE_MS;
    let nextSample = Date.now() + 60_000;
    let nextMessage = Date.now() + at(0.03) * 60_000;
    let messageOff = 0;
    let nextMusic = Date.now() + at(0.08) * 60_000;
    let musicOff = 0;
    let nextTimerReset = Date.now() + 30 * 60_000;
    const backupAt = startedAt + at(0.17) * 60_000;
    const pauseAt = startedAt + at(0.47) * 60_000;
    const resumeAt = startedAt + at(0.53) * 60_000;
    let backupSet = false;
    let paused = false;
    let resumed = false;
    let slideChanges = 0;

    const sample = async () => {
      const mainProcs = await processes(app);
      const nodeProcs = node ? await processes(node.app) : [];
      const merged = new Map<string, ProcessSample>();
      for (const p of mainProcs) {
        const was = merged.get(p.label) ?? { label: p.label, memoryMb: 0, cpu: 0 };
        merged.set(p.label, {
          label: p.label,
          memoryMb: was.memoryMb + p.memoryKb / 1024,
          cpu: was.cpu + p.cpu,
        });
      }
      merged.set('Node (all of it)', {
        label: 'Node (all of it)',
        memoryMb: nodeProcs.reduce((s, p) => s + p.memoryKb / 1024, 0),
        cpu: nodeProcs.reduce((s, p) => s + p.cpu, 0),
      });
      const screens = outputPages(app);
      const outputs: OutputSample[] = [];
      for (const [i, page] of screens.entries())
        outputs.push(await screenSample(page, `Main output ${String(i + 1)}`, seen));
      outputs.push(await screenSample(nodeOutput, 'Node output', seen));
      const stream = await win.evaluate(() => (globalThis as PageGlobals).drashti.stream.status());
      const net = await win.evaluate(() => (globalThis as PageGlobals).drashti.network.status());
      const nodes = await win.evaluate(() => (globalThis as PageGlobals).drashti.nodes.status());
      const watchdog =
        (await app.evaluate(
          () =>
            (
              globalThis as unknown as { drashtiDiagnostics?: { watchdog: { events: { kind: string }[] } } }
            ).drashtiDiagnostics?.watchdog.events.filter((e) =>
              ['crashed', 'hung', 'gave-up'].includes(e.kind),
            ).length ?? 0,
        )) + (node ? watchdogLines(node.userData) : 0);
      const disk = statfsSync(work);
      const s: SoakSample = {
        minute: minute(),
        at: new Date().toISOString(),
        processes: [...merged.values()],
        outputs,
        logMb: folderMb(join(userData, 'logs')) + (node ? folderMb(join(node.userData, 'logs')) : 0),
        freeDiskGb: (disk.bavail * disk.bsize) / 1024 ** 3,
        stream: {
          state: stream.live.state,
          recording: stream.recording.state,
          recordingMb: stream.recording.bytes / (1024 * 1024),
          fps: stream.live.fps,
          droppedFrames: stream.live.droppedFrames,
        },
        phoneConnected: net.connected > 0,
        nodeOnline: nodes.nodes.some((n) => n.online),
        watchdog,
      };
      samples.push(s);
      console.log(
        `soak ${String(s.minute)} min: Main ${String(Math.round(mainTotal([s])[0]?.[1] ?? 0))} MB, node ${String(Math.round(s.processes.find((p) => p.label === 'Node (all of it)')?.memoryMb ?? 0))} MB, p90 ${outputs.map((o) => String(o.p90Ms)).join('/')} ms, late ${outputs.map((o) => String(o.lateFrames)).join('/')}, black ${String(outputs.some((o) => o.black))}, stream ${s.stream.state}, ${String(slideChanges)} slide changes`,
      );
      writeReport(OUT, report([]));
    };

    while (Date.now() < end && exits.length === 0) {
      const now = Date.now();
      if (now >= nextSlide) {
        const r = await dispatch({ type: 'next' });
        if (r.ok && r.changed) slideChanges++;
        else await startOver();
        nextSlide += SLIDE_MS;
      }
      if (now >= nextMessage) {
        await dispatch({
          type: 'showMessage',
          message: { id: 'soak-parking', text: 'Car SOAK please move' },
        });
        messageOff = now + 60_000;
        nextMessage += 5 * 60_000;
      }
      if (messageOff > 0 && now >= messageOff) {
        await dispatch({ type: 'hideMessage', messageId: 'soak-parking' });
        messageOff = 0;
      }
      if (now >= nextMusic) {
        await win.evaluate((id) => (globalThis as PageGlobals).drashti.music.play(id), show.musicId);
        musicOff = now + 4 * 60_000;
        nextMusic += 20 * 60_000;
        note('music started');
      }
      if (musicOff > 0 && now >= musicOff) {
        await dispatch({ type: 'pauseMusic' });
        musicOff = 0;
      }
      if (now >= nextTimerReset) {
        await dispatch({ type: 'resetTimer', timerId: show.timerId });
        await dispatch({ type: 'startTimer', timerId: show.timerId });
        nextTimerReset += 30 * 60_000;
      }
      if (!backupSet && now >= backupAt - 2 * 60_000) {
        backupSet = true;
        const when = localWhen(minuteAfter(90_000));
        const saved = await win.evaluate(
          ({ folder, time }) =>
            (globalThis as PageGlobals).drashti.backups.save({
              enabled: true,
              folder,
              days: [0, 1, 2, 3, 4, 5, 6],
              time,
              keep: 7,
              media: true,
            }),
          { folder: backups, time: when.time },
        );
        expect(saved.ok).toBe(true);
        note(`a scheduled backup set for ${when.time}, while on air (it waits until the stream stops)`);
      }
      if (!paused && now >= pauseAt) {
        paused = true;
        await offAir();
      }
      if (paused && !resumed && now >= resumeAt) {
        resumed = true;
        await goLive();
      }
      if (now >= nextSample) {
        await sample();
        nextSample += SAMPLE_MS;
      }
      await sleep(250);
    }
    if (exits.length === 0) await sample();

    // ---- what it came to ---------------------------------------------------------------------------------
    const macroRuns = logCount(userData, /Macros: one runs by itself in ten seconds/u);
    const backupsMade = existsSync(join(backups, 'Drashti scheduled backups'))
      ? readdirSync(join(backups, 'Drashti scheduled backups')).filter((f) =>
          existsSync(join(backups, 'Drashti scheduled backups', f, 'backup.json')),
        ).length
      : 0;
    const black = samples.flatMap((s) =>
      s.outputs.filter((o) => o.black).map((o) => `${o.name} at ${String(s.minute)} min`),
    );
    const mainGrowth = growth(mainTotal(samples), MINUTES);
    const nodeGrowth = growth(memoryOf(samples, 'Node (all of it)'), MINUTES);
    const describe = (g: ReturnType<typeof growth>) =>
      `${String(Math.round(g.early))} MB after warming up, ${String(Math.round(g.late))} MB at the end; ${String(Math.round(g.perHour))} MB an hour (${String(Math.round(g.lastPerHour))} over the last third)`;
    const onAirSamples = samples.filter((s) => s.minute < at(0.47) - 1 || s.minute > at(0.53) + 2);
    const verdicts: Verdict[] = [
      {
        name: 'Drashti and the node ran the whole time',
        ok: exits.length === 0,
        detail: exits.join('; ') || 'no crash',
        fatal: true,
      },
      {
        name: 'No watchdog event (no window crashed, hung or was given up on)',
        ok: (samples.at(-1)?.watchdog ?? 0) === 0,
        detail: `${String(samples.at(-1)?.watchdog ?? 0)} event(s)`,
        fatal: true,
      },
      {
        name: 'No screen went black',
        ok: black.length === 0,
        detail: black.join(', ') || 'every screen showed something at every sample',
        fatal: true,
      },
      {
        name: "Main's memory did not keep growing",
        ok: !mainGrowth.keepsGrowing,
        detail: describe(mainGrowth),
        fatal: true,
      },
      {
        name: "The node's memory did not keep growing",
        ok: !nodeGrowth.keepsGrowing,
        detail: describe(nodeGrowth),
        fatal: true,
      },
      {
        name: 'The stream stayed on air and recorded (but for the pause between sabhas)',
        ok: onAirSamples.every((s) => s.stream.state === 'live' && s.stream.recording === 'recording'),
        detail:
          onAirSamples
            .filter((s) => s.stream.state !== 'live')
            .map((s) => `${String(s.minute)} min: ${s.stream.state}`)
            .join(', ') || 'on air at every sample',
        fatal: false,
      },
      {
        name: 'The phone stayed connected',
        ok: samples.every((s) => s.phoneConnected),
        detail: `${String(samples.filter((s) => !s.phoneConnected).length)} sample(s) without it`,
        fatal: false,
      },
      {
        name: 'The node stayed online',
        ok: samples.every((s) => s.nodeOnline),
        detail: `${String(samples.filter((s) => !s.nodeOnline).length)} sample(s) offline`,
        fatal: false,
      },
      {
        name: 'The scheduled macro went off at its times',
        ok: macroRuns >= macroTimes.filter((t) => t < end).length,
        detail: `${String(macroRuns)} of ${String(macroTimes.filter((t) => t < end).length)}`,
        fatal: false,
      },
      {
        name: 'The scheduled backup was made (after waiting while on air)',
        ok: backupsMade >= 1,
        detail: `${String(backupsMade)} backup(s)`,
        fatal: false,
      },
      {
        name: 'Slides kept changing',
        ok: slideChanges > (MINUTES * 60_000) / SLIDE_MS / 2,
        detail: `${String(slideChanges)} slide changes`,
        fatal: false,
      },
    ];
    writeReport(OUT, report(verdicts));
    for (const v of verdicts)
      console.log(`${v.ok ? 'PASS' : v.fatal ? 'FAIL' : 'WARN'}  ${v.name}: ${v.detail}`);
    for (const v of verdicts.filter((x) => x.fatal)) expect.soft(v.ok, `${v.name}: ${v.detail}`).toBe(true);
  } finally {
    rtmp?.stop();
    await phone?.close().catch(() => undefined);
    if (main && exits.length === 0)
      await main.win
        .evaluate(async () => {
          const d = (globalThis as PageGlobals).drashti;
          await d.stream.end({ confirmed: true });
          await d.stream.stopRecording();
        })
        .catch(() => undefined);
    await node?.app.close().catch(() => undefined);
    await main?.app.close().catch(() => undefined);
  }
});
