/*
 * Every icon Drashti uses, in one place: Lucide (ISC licence, see
 * LICENSES/icons). Import icons from here, never from lucide-react directly,
 * so the set stays small and consistent. An icon is never the only label:
 * buttons have text, or an aria-label and a tooltip (IconButton).
 */
export type { LucideIcon as Icon } from 'lucide-react';
export { Camera, CircleDot, HardDrive, KeyRound, Mic, Radio, Video, Wifi, WifiOff } from 'lucide-react';
// The local network: phones and tablets, pairing by QR code, the announcements poster.
export { Megaphone, Printer, QrCode, Smartphone, TabletSmartphone } from 'lucide-react';
// Announcements from phones: the queue, and the ticker they can scroll in.
export { Inbox, ScrollText, Send } from 'lucide-react';
// Looks (what each screen group shows), stage layouts, masks, key and fill, macros and MIDI.
export { Blend, Frame, KeyboardMusic, LayoutTemplate, SwatchBook, Zap } from 'lucide-react';
// Shastra texts, the arti, the calendar and the idle rotation (Session 12).
export { BookOpen, CalendarDays, Flame, GalleryHorizontalEnd, Quote } from 'lucide-react';
// Roles and PINs, scheduled backups, updates, music and markers (Session 14).
export { Download, LockOpen, RefreshCw, ShieldCheck } from 'lucide-react';
export {
  AlertTriangle,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpToLine,
  AudioLines,
  Ban,
  BookTemplate,
  BringToFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  CopyPlus,
  Eraser,
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  Film,
  Folder,
  FolderOpen,
  FolderPlus,
  GripVertical,
  Image,
  ImagePlus,
  Import,
  Info,
  Italic,
  Keyboard,
  Languages,
  Layers,
  LayoutGrid,
  ListFilter,
  ListMusic,
  ListPlus,
  Loader,
  Lock,
  Magnet,
  Maximize2,
  Minus,
  MessageSquare,
  Monitor,
  MonitorOff,
  MonitorSpeaker,
  MoreHorizontal,
  Music,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Presentation,
  RectangleHorizontal,
  Redo2,
  Repeat,
  RotateCcw,
  RotateCw,
  ScanEye,
  Search,
  SendToBack,
  Settings,
  Shapes,
  SkipBack,
  SkipForward,
  Square,
  SquareDashed,
  SquarePen,
  Stamp,
  StepBack,
  StepForward,
  Sticker,
  Timer,
  Trash2,
  Tv,
  Type,
  Undo2,
  Unlock,
  Upload,
  Volume2,
  VolumeX,
  Wand2,
  X,
} from 'lucide-react';
