/*
 * Every icon Drashti uses, in one place: Lucide (ISC licence, see
 * LICENSES/icons). Import icons from here, never from lucide-react directly,
 * so the set stays small and consistent. An icon is never the only label:
 * buttons have text, or an aria-label and a tooltip (IconButton).
 */
export type { LucideIcon as Icon } from 'lucide-react';
export {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Ban,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  Eraser,
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  Film,
  Folder,
  FolderOpen,
  FolderPlus,
  GripVertical,
  Image,
  Import,
  Info,
  Keyboard,
  Layers,
  LayoutGrid,
  ListMusic,
  ListPlus,
  Loader,
  Lock,
  Maximize2,
  MessageSquare,
  Monitor,
  MonitorOff,
  MonitorSpeaker,
  MoreHorizontal,
  Music,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Presentation,
  Redo2,
  RotateCcw,
  Search,
  Settings,
  SkipBack,
  SkipForward,
  Square,
  Stamp,
  StepBack,
  StepForward,
  Sticker,
  Timer,
  Trash2,
  Tv,
  Type,
  Undo2,
  Unlock,
  Upload,
  Volume2,
  VolumeX,
  X,
} from 'lucide-react';
